stages:
- build-standardx8664
- build-rpiarmhf
- build-rpiaarch64

build-standardx8664:
  stage: build-standardx8664
  script:
    - git checkout release/standardx8664
    - git pull origin release/standardx8664
    - git pull --recurse-submodules
    - git submodule update --remote --recursive  
    - make build-standard-x8664-iso
  only:
    - release/standardx8664
    - develop/standardx8664

build-rpiarmhf:
  stage: build-rpiarmhf
  script:
    - git checkout release/rpiarmhf
    - git pull origin release/rpiarmhf
    - git pull --recurse-submodules
    - git submodule update --remote --recursive  
    - make build-rpi-armhf-iso
  only:
    - release/rpiarmhf
    - develop/rpiarmhf
